#Environment Configuration 
import streamlit as st
import os
import json
import re
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from langchain_openai import ChatOpenAI
from langchain_core.messages import HumanMessage, SystemMessage
from fpdf import FPDF

# Step 0: Set-up

# Page Configuration
st.set_page_config(
    page_title="Restaurant Menu Optimiser",
    page_icon="🍽️",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Progression Bar
steps_complete = sum([
    "df" in st.session_state,
    "classification" in st.session_state.get("df", {}).columns if "df" in st.session_state else False,
    "recommendations" in st.session_state,
    "pdf" in st.session_state
])
st.progress(steps_complete / 4, text=f"Progress: {steps_complete}/4 steps complete")

# Header
st.title("Restaurant Menu Optimiser")
st.caption("Upload your menu data to get AI-powered pricing recommendations and margin optimisation.")

# Sidebar 

api_key = None
if hasattr(st, "secrets"):
    api_key = st.secrets.get("OPENAI_API_KEY")
if not api_key:
    api_key = os.getenv("OPENAI_API_KEY")
if not api_key:
    api_key = st.sidebar.text_input("Enter your OpenAI API key", type="password")

model = st.sidebar.selectbox("Model", ["gpt-4o-mini"])
temperature = st.sidebar.slider("Temperature", 0.0, 1.0, 0.2)

llm = ChatOpenAI(
    model=model,
    temperature=temperature,
    api_key=api_key
) if api_key else None

st.sidebar.markdown("---")
st.sidebar.markdown("### Required CSV Columns")
st.sidebar.markdown("""
- `item_name`
- `category`
- `current_price`
- `food_cost`
- `monthly_units_sold`
""")

# PDF Generator 
def generate_pdf(df, recommendations, summary):
    pdf = FPDF()
    pdf.add_page()

    # Title
    pdf.set_font("Times", "B", 18)
    pdf.cell(0, 12, "Menu Optimisation Report", ln=True, align="C")
    pdf.set_font("Times", size=9)
    pdf.cell(0, 6, "Generated by AI Restaurant Menu Optimiser", ln=True, align="C")
    pdf.ln(4)

    # Summary metrics
    pdf.set_font("Times", "B", 12)
    pdf.cell(0, 8, "Performance Overview", ln=True)
    pdf.set_font("Times", size=10)
    pdf.cell(0, 6, f"Total Monthly Revenue:  £{df['monthly_revenue'].sum():,.2f}", ln=True)
    pdf.cell(0, 6, f"Total Monthly Profit:   £{df['monthly_profit'].sum():,.2f}", ln=True)
    pdf.cell(0, 6, f"Average Margin:         {df['margin_pct'].mean():.1f}%", ln=True)
    pdf.ln(4)

    # Executive summary
    pdf.set_font("Times", "B", 12)
    pdf.cell(0, 8, "Executive Summary", ln=True)
    pdf.set_font("Times", size=10)
    pdf.multi_cell(0, 6, summary)
    pdf.ln(4)
    
        # Classifications
    pdf.set_font("Times", "B", 12)
    pdf.cell(0, 8, "Menu Engineering Classifications", ln=True)
    pdf.set_font("Times", "B", 9)
    headers = ["Item", "Category", "Price", "Food Cost", "Margin%", "Units/Mo", "Class"]
    widths =  [45,      22,         18,      20,          18,        20,         30]
    for h, w in zip(headers, widths):
        pdf.cell(w, 7, h, border=1)
    pdf.ln()
    pdf.set_font("Times", size=9)
    for _, row in df.iterrows():
        pdf.cell(45, 6, str(row["item_name"])[:22], border=1)
        pdf.cell(22, 6, str(row["category"])[:12], border=1)
        pdf.cell(18, 6, f"£{row['current_price']:.2f}", border=1)
        pdf.cell(20, 6, f"£{row['food_cost']:.2f}", border=1)
        pdf.cell(18, 6, f"{row['margin_pct']:.1f}%", border=1)
        pdf.cell(20, 6, str(int(row["monthly_units_sold"])), border=1)
        pdf.cell(30, 6, str(row["classification"])[:16], border=1)
        pdf.ln()
    pdf.ln(4)

    # Recommendations
    pdf.set_font("Times", "B", 12)
    pdf.cell(0, 8, "AI Pricing Recommendations", ln=True)
    for rec in recommendations:
        pdf.set_font("Times", "B", 10)
        pdf.cell(0, 7, f"{rec.get('item_name', '')} — {rec.get('action', '')}", ln=True)
        pdf.set_font("Times", size=9)
        curr = rec.get('current_price', 0)
        rec_p = rec.get('recommended_price', 0)
        pdf.cell(0, 6, f"  Price: £{curr:.2f} → £{rec_p:.2f}  |  Impact: {rec.get('projected_monthly_impact', 'N/A')}", ln=True)
        pdf.multi_cell(0, 6, f"  {rec.get('reasoning', '')}")
        pdf.ln(1)
        
    output = pdf.output(dest="S")
    return output if isinstance(output, bytes) else output.encode("latin-1")

# Step 1: Upload and Validation
st.markdown('<div class="step-header">Step 1 — Upload & Validate Menu Data</div>', unsafe_allow_html=True)

uploaded_file = st.file_uploader(
    "Upload your menu spreadsheet",
    type=["csv", "xlsx"],
    help="Must contain: item_name, category, current_price, food_cost, monthly_units_sold"
)

if st.button("✅ Validate Data", disabled=uploaded_file is None):
    try:
        if uploaded_file.name.endswith(".csv"):
            df_raw = pd.read_csv(uploaded_file)
        else:
            df_raw = pd.read_excel(uploaded_file)

        required_cols = ["item_name", "category", "current_price",
                         "food_cost", "monthly_units_sold"]
        missing = [c for c in required_cols if c not in df_raw.columns]

        if missing:
            st.error(f"❌ Missing columns: {missing}")
            st.info("Please check your spreadsheet has the correct column names.")
        else:
            # Calculate derived metrics
            df_raw["gross_margin"]    = df_raw["current_price"] - df_raw["food_cost"]
            df_raw["margin_pct"]      = (df_raw["gross_margin"] / df_raw["current_price"]) * 100
            df_raw["monthly_revenue"] = df_raw["current_price"] * df_raw["monthly_units_sold"]
            df_raw["monthly_profit"]  = df_raw["gross_margin"]  * df_raw["monthly_units_sold"]

            st.session_state["df"] = df_raw
            st.session_state.pop("recommendations", None)
            st.session_state.pop("summary", None)
            st.success(f"✅ Data validated — {len(df_raw)} menu items loaded.")

    except Exception as e:
        st.error(f"Failed to read file: {e}")
        
if "df" in st.session_state:
    df = st.session_state["df"]

    # Summary metrics
    col1, col2, col3, col4 = st.columns(4)
    col1.metric("Total Items",        len(df))
    col2.metric("Monthly Revenue",    f"£{df['monthly_revenue'].sum():,.2f}")
    col3.metric("Monthly Profit",     f"£{df['monthly_profit'].sum():,.2f}")
    col4.metric("Avg Margin",         f"{df['margin_pct'].mean():.1f}%")

    st.dataframe(
        df[["item_name", "category", "current_price", "food_cost",
            "margin_pct", "monthly_units_sold", "monthly_profit"]]
        .rename(columns={
            "item_name": "Item", "category": "Category",
            "current_price": "Price (£)", "food_cost": "Food Cost (£)",
            "margin_pct": "Margin %", "monthly_units_sold": "Units/Month",
            "monthly_profit": "Monthly Profit (£)"
        }),
        use_container_width=True
    )
